import { MigrationInterface, QueryRunner } from "typeorm";

export class AddDeviceAndBiometricSupport1750109457293 implements MigrationInterface {
    name = 'AddDeviceAndBiometricSupport1750109457293'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "userId" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "reasonRevoked" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c31d0a2f38e6e99110df62ab0af" UNIQUE ("token"))`);
        await queryRunner.query(`INSERT INTO "temporary_refresh_tokens"("id", "token", "userId", "expiresAt", "isRevoked", "reasonRevoked", "createdAt", "updatedAt") SELECT "id", "token", "userId", "expiresAt", "isRevoked", "reasonRevoked", "createdAt", "updatedAt" FROM "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`ALTER TABLE "temporary_refresh_tokens" RENAME TO "refresh_tokens"`);
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "firstName" varchar, "lastName" varchar, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"))`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
        await queryRunner.query(`CREATE TABLE "device_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "user_id" varchar NOT NULL, "deviceType" varchar, "deviceName" varchar, "deviceModel" varchar, "osVersion" varchar, "isAdminDevice" boolean NOT NULL DEFAULT (0), "isBiometricEnabled" boolean NOT NULL DEFAULT (0), "biometricType" varchar, "isActive" boolean NOT NULL DEFAULT (1), "lastUsed" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "temporary_refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c31d0a2f38e6e99110df62ab0af" UNIQUE ("token"))`);
        await queryRunner.query(`INSERT INTO "temporary_refresh_tokens"("id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt") SELECT "id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt" FROM "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`ALTER TABLE "temporary_refresh_tokens" RENAME TO "refresh_tokens"`);
        await queryRunner.query(`CREATE TABLE "temporary_refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar NOT NULL, "device_id" varchar, "revokedReason" varchar, CONSTRAINT "UQ_c31d0a2f38e6e99110df62ab0af" UNIQUE ("token"))`);
        await queryRunner.query(`INSERT INTO "temporary_refresh_tokens"("id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt") SELECT "id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt" FROM "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`ALTER TABLE "temporary_refresh_tokens" RENAME TO "refresh_tokens"`);
        await queryRunner.query(`CREATE TABLE "temporary_refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar NOT NULL, "device_id" varchar, "revokedReason" varchar, CONSTRAINT "UQ_c31d0a2f38e6e99110df62ab0af" UNIQUE ("token"))`);
        await queryRunner.query(`INSERT INTO "temporary_refresh_tokens"("id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt", "user_id", "device_id", "revokedReason") SELECT "id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt", "user_id", "device_id", "revokedReason" FROM "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`ALTER TABLE "temporary_refresh_tokens" RENAME TO "refresh_tokens"`);
        await queryRunner.query(`CREATE TABLE "temporary_barrels" ("id" varchar PRIMARY KEY NOT NULL, "size" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT (0), "orderNumber" integer NOT NULL, "remainingBeers" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "totalBeers" integer NOT NULL)`);
        await queryRunner.query(`INSERT INTO "temporary_barrels"("id", "size", "isActive", "orderNumber", "remainingBeers", "createdAt", "updatedAt", "deletedAt", "totalBeers") SELECT "id", "size", "isActive", "orderNumber", "remainingBeers", "createdAt", "updatedAt", "deletedAt", "totalBeers" FROM "barrels"`);
        await queryRunner.query(`DROP TABLE "barrels"`);
        await queryRunner.query(`ALTER TABLE "temporary_barrels" RENAME TO "barrels"`);
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "firstName" varchar, "lastName" varchar, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"))`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
        await queryRunner.query(`CREATE TABLE "temporary_device_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "user_id" varchar NOT NULL, "deviceType" varchar, "deviceName" varchar, "deviceModel" varchar, "osVersion" varchar, "isAdminDevice" boolean NOT NULL DEFAULT (0), "isBiometricEnabled" boolean NOT NULL DEFAULT (0), "biometricType" varchar, "isActive" boolean NOT NULL DEFAULT (1), "lastUsed" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_17e1f528b993c6d55def4cf5bea" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_device_tokens"("id", "token", "user_id", "deviceType", "deviceName", "deviceModel", "osVersion", "isAdminDevice", "isBiometricEnabled", "biometricType", "isActive", "lastUsed", "createdAt", "updatedAt") SELECT "id", "token", "user_id", "deviceType", "deviceName", "deviceModel", "osVersion", "isAdminDevice", "isBiometricEnabled", "biometricType", "isActive", "lastUsed", "createdAt", "updatedAt" FROM "device_tokens"`);
        await queryRunner.query(`DROP TABLE "device_tokens"`);
        await queryRunner.query(`ALTER TABLE "temporary_device_tokens" RENAME TO "device_tokens"`);
        await queryRunner.query(`CREATE TABLE "temporary_refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar NOT NULL, "device_id" varchar, "revokedReason" varchar, CONSTRAINT "UQ_c31d0a2f38e6e99110df62ab0af" UNIQUE ("token"), CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_443e94ab8ae68be5d2beb2b8110" FOREIGN KEY ("device_id") REFERENCES "device_tokens" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_refresh_tokens"("id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt", "user_id", "device_id", "revokedReason") SELECT "id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt", "user_id", "device_id", "revokedReason" FROM "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`ALTER TABLE "temporary_refresh_tokens" RENAME TO "refresh_tokens"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" RENAME TO "temporary_refresh_tokens"`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar NOT NULL, "device_id" varchar, "revokedReason" varchar, CONSTRAINT "UQ_c31d0a2f38e6e99110df62ab0af" UNIQUE ("token"))`);
        await queryRunner.query(`INSERT INTO "refresh_tokens"("id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt", "user_id", "device_id", "revokedReason") SELECT "id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt", "user_id", "device_id", "revokedReason" FROM "temporary_refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "temporary_refresh_tokens"`);
        await queryRunner.query(`ALTER TABLE "device_tokens" RENAME TO "temporary_device_tokens"`);
        await queryRunner.query(`CREATE TABLE "device_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "user_id" varchar NOT NULL, "deviceType" varchar, "deviceName" varchar, "deviceModel" varchar, "osVersion" varchar, "isAdminDevice" boolean NOT NULL DEFAULT (0), "isBiometricEnabled" boolean NOT NULL DEFAULT (0), "biometricType" varchar, "isActive" boolean NOT NULL DEFAULT (1), "lastUsed" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "device_tokens"("id", "token", "user_id", "deviceType", "deviceName", "deviceModel", "osVersion", "isAdminDevice", "isBiometricEnabled", "biometricType", "isActive", "lastUsed", "createdAt", "updatedAt") SELECT "id", "token", "user_id", "deviceType", "deviceName", "deviceModel", "osVersion", "isAdminDevice", "isBiometricEnabled", "biometricType", "isActive", "lastUsed", "createdAt", "updatedAt" FROM "temporary_device_tokens"`);
        await queryRunner.query(`DROP TABLE "temporary_device_tokens"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "firstName" varchar, "lastName" varchar, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"))`);
        await queryRunner.query(`INSERT INTO "users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
        await queryRunner.query(`ALTER TABLE "barrels" RENAME TO "temporary_barrels"`);
        await queryRunner.query(`CREATE TABLE "barrels" ("id" varchar PRIMARY KEY NOT NULL, "size" integer NOT NULL, "isActive" boolean NOT NULL DEFAULT (1), "orderNumber" integer NOT NULL, "remainingBeers" integer NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "totalBeers" integer NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "barrels"("id", "size", "isActive", "orderNumber", "remainingBeers", "createdAt", "updatedAt", "deletedAt", "totalBeers") SELECT "id", "size", "isActive", "orderNumber", "remainingBeers", "createdAt", "updatedAt", "deletedAt", "totalBeers" FROM "temporary_barrels"`);
        await queryRunner.query(`DROP TABLE "temporary_barrels"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" RENAME TO "temporary_refresh_tokens"`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar NOT NULL, "device_id" varchar, "revokedReason" varchar, CONSTRAINT "UQ_c31d0a2f38e6e99110df62ab0af" UNIQUE ("token"))`);
        await queryRunner.query(`INSERT INTO "refresh_tokens"("id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt", "user_id", "device_id", "revokedReason") SELECT "id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt", "user_id", "device_id", "revokedReason" FROM "temporary_refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "temporary_refresh_tokens"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" RENAME TO "temporary_refresh_tokens"`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c31d0a2f38e6e99110df62ab0af" UNIQUE ("token"))`);
        await queryRunner.query(`INSERT INTO "refresh_tokens"("id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt") SELECT "id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt" FROM "temporary_refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "temporary_refresh_tokens"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" RENAME TO "temporary_refresh_tokens"`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "userId" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "reasonRevoked" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c31d0a2f38e6e99110df62ab0af" UNIQUE ("token"))`);
        await queryRunner.query(`INSERT INTO "refresh_tokens"("id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt") SELECT "id", "token", "expiresAt", "isRevoked", "createdAt", "updatedAt" FROM "temporary_refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "temporary_refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "device_tokens"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "firstName" varchar, "lastName" varchar, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"))`);
        await queryRunner.query(`INSERT INTO "users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" RENAME TO "temporary_refresh_tokens"`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "userId" varchar NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "reasonRevoked" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c31d0a2f38e6e99110df62ab0af" UNIQUE ("token"), CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "refresh_tokens"("id", "token", "userId", "expiresAt", "isRevoked", "reasonRevoked", "createdAt", "updatedAt") SELECT "id", "token", "userId", "expiresAt", "isRevoked", "reasonRevoked", "createdAt", "updatedAt" FROM "temporary_refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "temporary_refresh_tokens"`);
    }

}
