import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSpilledBeerCountToUser1757950326550 implements MigrationInterface {
    name = 'AddSpilledBeerCountToUser1757950326550'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "firstName" varchar, "lastName" varchar, "profilePicture" varchar, "spilledBeerCount" integer NOT NULL DEFAULT (0), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "firstName" varchar, "lastName" varchar, "profilePicture" varchar, "spilledBeerCount" integer NOT NULL DEFAULT (0), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "firstName" varchar, "lastName" varchar, "profilePicture" varchar, "spilledBeerCount" integer NOT NULL DEFAULT (0), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "firstName" varchar, "lastName" varchar, "profilePicture" varchar, "spilledBeerCount" integer NOT NULL DEFAULT (0), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
    }

}
