import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSpilledToEventBeer1757950602334 implements MigrationInterface {
    name = 'AddSpilledToEventBeer1757950602334'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "firstName" varchar, "lastName" varchar, "profilePicture" varchar, "spilledBeerCount" integer NOT NULL DEFAULT (0), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"))`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
        await queryRunner.query(`CREATE TABLE "temporary_event_beers" ("id" varchar PRIMARY KEY NOT NULL, "eventId" varchar NOT NULL, "userId" varchar NOT NULL, "barrelId" varchar, "consumedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "spilled" boolean NOT NULL DEFAULT (0), CONSTRAINT "FK_a5acb3773ab1a268feb1cd311ec" FOREIGN KEY ("barrelId") REFERENCES "barrels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_a32df1f52f94a5caaeae4572bfc" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_99a249e32b468dbc3e92a60968e" FOREIGN KEY ("eventId") REFERENCES "event" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_event_beers"("id", "eventId", "userId", "barrelId", "consumedAt", "deletedAt") SELECT "id", "eventId", "userId", "barrelId", "consumedAt", "deletedAt" FROM "event_beers"`);
        await queryRunner.query(`DROP TABLE "event_beers"`);
        await queryRunner.query(`ALTER TABLE "temporary_event_beers" RENAME TO "event_beers"`);
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "firstName" varchar, "lastName" varchar, "profilePicture" varchar, "spilledBeerCount" integer NOT NULL DEFAULT (0), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"))`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "firstName" varchar, "lastName" varchar, "profilePicture" varchar, "spilledBeerCount" integer NOT NULL DEFAULT (0), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"))`);
        await queryRunner.query(`INSERT INTO "users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
        await queryRunner.query(`ALTER TABLE "event_beers" RENAME TO "temporary_event_beers"`);
        await queryRunner.query(`CREATE TABLE "event_beers" ("id" varchar PRIMARY KEY NOT NULL, "eventId" varchar NOT NULL, "userId" varchar NOT NULL, "barrelId" varchar, "consumedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "FK_a5acb3773ab1a268feb1cd311ec" FOREIGN KEY ("barrelId") REFERENCES "barrels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_a32df1f52f94a5caaeae4572bfc" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_99a249e32b468dbc3e92a60968e" FOREIGN KEY ("eventId") REFERENCES "event" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "event_beers"("id", "eventId", "userId", "barrelId", "consumedAt", "deletedAt") SELECT "id", "eventId", "userId", "barrelId", "consumedAt", "deletedAt" FROM "temporary_event_beers"`);
        await queryRunner.query(`DROP TABLE "temporary_event_beers"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, "firstName" varchar, "lastName" varchar, "profilePicture" varchar, "spilledBeerCount" integer NOT NULL DEFAULT (0), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"))`);
        await queryRunner.query(`INSERT INTO "users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt", "firstName", "lastName", "profilePicture", "spilledBeerCount" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
    }

}
