import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateEventBeersTable1749757491913 implements MigrationInterface {
    name = 'CreateEventBeersTable1749757491913'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_device_token_token"`);
        await queryRunner.query(`CREATE TABLE "temporary_device_token" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "deviceType" varchar NOT NULL DEFAULT ('web'), "deviceName" varchar, "deviceModel" varchar, "osVersion" varchar, "isActive" boolean NOT NULL DEFAULT (1), "lastUsed" datetime, "userId" varchar NOT NULL, "isAdminDevice" boolean NOT NULL DEFAULT (0), "biometricEnabled" boolean, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "temporary_device_token"("id", "token", "deviceType", "deviceName", "deviceModel", "osVersion", "isActive", "lastUsed", "userId", "isAdminDevice", "biometricEnabled", "createdAt", "updatedAt") SELECT "id", "token", "deviceType", "deviceName", "deviceModel", "osVersion", "isActive", "lastUsed", "userId", "isAdminDevice", "biometricEnabled", "createdAt", "updatedAt" FROM "device_token"`);
        await queryRunner.query(`DROP TABLE "device_token"`);
        await queryRunner.query(`ALTER TABLE "temporary_device_token" RENAME TO "device_token"`);
        await queryRunner.query(`CREATE INDEX "IDX_device_token_token" ON "device_token" ("token") `);
        await queryRunner.query(`CREATE TABLE "temporary_beers" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "barrelId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "temporary_beers"("id", "userId", "barrelId", "createdAt", "deletedAt") SELECT "id", "userId", "barrelId", "createdAt", "deletedAt" FROM "beers"`);
        await queryRunner.query(`DROP TABLE "beers"`);
        await queryRunner.query(`ALTER TABLE "temporary_beers" RENAME TO "beers"`);
        await queryRunner.query(`CREATE TABLE "temporary_event_users" ("event_id" varchar NOT NULL, "user_id" varchar NOT NULL, PRIMARY KEY ("event_id", "user_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_event_users"("event_id", "user_id") SELECT "event_id", "user_id" FROM "event_users"`);
        await queryRunner.query(`DROP TABLE "event_users"`);
        await queryRunner.query(`ALTER TABLE "temporary_event_users" RENAME TO "event_users"`);
        await queryRunner.query(`CREATE TABLE "temporary_event_barrels" ("event_id" varchar NOT NULL, "barrel_id" varchar NOT NULL, PRIMARY KEY ("event_id", "barrel_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_event_barrels"("event_id", "barrel_id") SELECT "event_id", "barrel_id" FROM "event_barrels"`);
        await queryRunner.query(`DROP TABLE "event_barrels"`);
        await queryRunner.query(`ALTER TABLE "temporary_event_barrels" RENAME TO "event_barrels"`);
        await queryRunner.query(`DROP INDEX "IDX_device_token_token"`);
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"))`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
        await queryRunner.query(`CREATE TABLE "event_beers" ("id" varchar PRIMARY KEY NOT NULL, "eventId" varchar NOT NULL, "userId" varchar NOT NULL, "barrelId" varchar, "consumedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime)`);
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar NOT NULL, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"))`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
        await queryRunner.query(`CREATE INDEX "IDX_60254057740731d5a0b07548f8" ON "event_users" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_60b09733c048fa94afb3581c62" ON "event_users" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6fbd0029e33c03a79e873c34b7" ON "event_barrels" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b50fc7fc51f6222996f863de90" ON "event_barrels" ("barrel_id") `);
        await queryRunner.query(`CREATE TABLE "temporary_device_token" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "deviceType" varchar NOT NULL DEFAULT ('web'), "deviceName" varchar, "deviceModel" varchar, "osVersion" varchar, "isActive" boolean NOT NULL DEFAULT (1), "lastUsed" datetime, "userId" varchar NOT NULL, "isAdminDevice" boolean NOT NULL DEFAULT (0), "biometricEnabled" boolean, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_ba0cbbc3097f061e197e71c112e" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_device_token"("id", "token", "deviceType", "deviceName", "deviceModel", "osVersion", "isActive", "lastUsed", "userId", "isAdminDevice", "biometricEnabled", "createdAt", "updatedAt") SELECT "id", "token", "deviceType", "deviceName", "deviceModel", "osVersion", "isActive", "lastUsed", "userId", "isAdminDevice", "biometricEnabled", "createdAt", "updatedAt" FROM "device_token"`);
        await queryRunner.query(`DROP TABLE "device_token"`);
        await queryRunner.query(`ALTER TABLE "temporary_device_token" RENAME TO "device_token"`);
        await queryRunner.query(`CREATE TABLE "temporary_beers" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "barrelId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "FK_f1e92622b7c7e82f3e9fe70feaa" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_2e5d57661845b481dcfb8082831" FOREIGN KEY ("barrelId") REFERENCES "barrels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_beers"("id", "userId", "barrelId", "createdAt", "deletedAt") SELECT "id", "userId", "barrelId", "createdAt", "deletedAt" FROM "beers"`);
        await queryRunner.query(`DROP TABLE "beers"`);
        await queryRunner.query(`ALTER TABLE "temporary_beers" RENAME TO "beers"`);
        await queryRunner.query(`CREATE TABLE "temporary_event_beers" ("id" varchar PRIMARY KEY NOT NULL, "eventId" varchar NOT NULL, "userId" varchar NOT NULL, "barrelId" varchar, "consumedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "FK_99a249e32b468dbc3e92a60968e" FOREIGN KEY ("eventId") REFERENCES "event" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_a32df1f52f94a5caaeae4572bfc" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_a5acb3773ab1a268feb1cd311ec" FOREIGN KEY ("barrelId") REFERENCES "barrels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_event_beers"("id", "eventId", "userId", "barrelId", "consumedAt", "deletedAt") SELECT "id", "eventId", "userId", "barrelId", "consumedAt", "deletedAt" FROM "event_beers"`);
        await queryRunner.query(`DROP TABLE "event_beers"`);
        await queryRunner.query(`ALTER TABLE "temporary_event_beers" RENAME TO "event_beers"`);
        await queryRunner.query(`DROP INDEX "IDX_60254057740731d5a0b07548f8"`);
        await queryRunner.query(`DROP INDEX "IDX_60b09733c048fa94afb3581c62"`);
        await queryRunner.query(`CREATE TABLE "temporary_event_users" ("event_id" varchar NOT NULL, "user_id" varchar NOT NULL, CONSTRAINT "FK_60254057740731d5a0b07548f82" FOREIGN KEY ("event_id") REFERENCES "event" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_60b09733c048fa94afb3581c62d" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("event_id", "user_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_event_users"("event_id", "user_id") SELECT "event_id", "user_id" FROM "event_users"`);
        await queryRunner.query(`DROP TABLE "event_users"`);
        await queryRunner.query(`ALTER TABLE "temporary_event_users" RENAME TO "event_users"`);
        await queryRunner.query(`CREATE INDEX "IDX_60254057740731d5a0b07548f8" ON "event_users" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_60b09733c048fa94afb3581c62" ON "event_users" ("user_id") `);
        await queryRunner.query(`DROP INDEX "IDX_6fbd0029e33c03a79e873c34b7"`);
        await queryRunner.query(`DROP INDEX "IDX_b50fc7fc51f6222996f863de90"`);
        await queryRunner.query(`CREATE TABLE "temporary_event_barrels" ("event_id" varchar NOT NULL, "barrel_id" varchar NOT NULL, CONSTRAINT "FK_6fbd0029e33c03a79e873c34b78" FOREIGN KEY ("event_id") REFERENCES "event" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_b50fc7fc51f6222996f863de909" FOREIGN KEY ("barrel_id") REFERENCES "barrels" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("event_id", "barrel_id"))`);
        await queryRunner.query(`INSERT INTO "temporary_event_barrels"("event_id", "barrel_id") SELECT "event_id", "barrel_id" FROM "event_barrels"`);
        await queryRunner.query(`DROP TABLE "event_barrels"`);
        await queryRunner.query(`ALTER TABLE "temporary_event_barrels" RENAME TO "event_barrels"`);
        await queryRunner.query(`CREATE INDEX "IDX_6fbd0029e33c03a79e873c34b7" ON "event_barrels" ("event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b50fc7fc51f6222996f863de90" ON "event_barrels" ("barrel_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_b50fc7fc51f6222996f863de90"`);
        await queryRunner.query(`DROP INDEX "IDX_6fbd0029e33c03a79e873c34b7"`);
        await queryRunner.query(`ALTER TABLE "event_barrels" RENAME TO "temporary_event_barrels"`);
        await queryRunner.query(`CREATE TABLE "event_barrels" ("event_id" varchar NOT NULL, "barrel_id" varchar NOT NULL, PRIMARY KEY ("event_id", "barrel_id"))`);
        await queryRunner.query(`INSERT INTO "event_barrels"("event_id", "barrel_id") SELECT "event_id", "barrel_id" FROM "temporary_event_barrels"`);
        await queryRunner.query(`DROP TABLE "temporary_event_barrels"`);
        await queryRunner.query(`CREATE INDEX "IDX_b50fc7fc51f6222996f863de90" ON "event_barrels" ("barrel_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6fbd0029e33c03a79e873c34b7" ON "event_barrels" ("event_id") `);
        await queryRunner.query(`DROP INDEX "IDX_60b09733c048fa94afb3581c62"`);
        await queryRunner.query(`DROP INDEX "IDX_60254057740731d5a0b07548f8"`);
        await queryRunner.query(`ALTER TABLE "event_users" RENAME TO "temporary_event_users"`);
        await queryRunner.query(`CREATE TABLE "event_users" ("event_id" varchar NOT NULL, "user_id" varchar NOT NULL, PRIMARY KEY ("event_id", "user_id"))`);
        await queryRunner.query(`INSERT INTO "event_users"("event_id", "user_id") SELECT "event_id", "user_id" FROM "temporary_event_users"`);
        await queryRunner.query(`DROP TABLE "temporary_event_users"`);
        await queryRunner.query(`CREATE INDEX "IDX_60b09733c048fa94afb3581c62" ON "event_users" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_60254057740731d5a0b07548f8" ON "event_users" ("event_id") `);
        await queryRunner.query(`ALTER TABLE "event_beers" RENAME TO "temporary_event_beers"`);
        await queryRunner.query(`CREATE TABLE "event_beers" ("id" varchar PRIMARY KEY NOT NULL, "eventId" varchar NOT NULL, "userId" varchar NOT NULL, "barrelId" varchar, "consumedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "event_beers"("id", "eventId", "userId", "barrelId", "consumedAt", "deletedAt") SELECT "id", "eventId", "userId", "barrelId", "consumedAt", "deletedAt" FROM "temporary_event_beers"`);
        await queryRunner.query(`DROP TABLE "temporary_event_beers"`);
        await queryRunner.query(`ALTER TABLE "beers" RENAME TO "temporary_beers"`);
        await queryRunner.query(`CREATE TABLE "beers" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "barrelId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime)`);
        await queryRunner.query(`INSERT INTO "beers"("id", "userId", "barrelId", "createdAt", "deletedAt") SELECT "id", "userId", "barrelId", "createdAt", "deletedAt" FROM "temporary_beers"`);
        await queryRunner.query(`DROP TABLE "temporary_beers"`);
        await queryRunner.query(`ALTER TABLE "device_token" RENAME TO "temporary_device_token"`);
        await queryRunner.query(`CREATE TABLE "device_token" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "deviceType" varchar NOT NULL DEFAULT ('web'), "deviceName" varchar, "deviceModel" varchar, "osVersion" varchar, "isActive" boolean NOT NULL DEFAULT (1), "lastUsed" datetime, "userId" varchar NOT NULL, "isAdminDevice" boolean NOT NULL DEFAULT (0), "biometricEnabled" boolean, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "device_token"("id", "token", "deviceType", "deviceName", "deviceModel", "osVersion", "isActive", "lastUsed", "userId", "isAdminDevice", "biometricEnabled", "createdAt", "updatedAt") SELECT "id", "token", "deviceType", "deviceName", "deviceModel", "osVersion", "isActive", "lastUsed", "userId", "isAdminDevice", "biometricEnabled", "createdAt", "updatedAt" FROM "temporary_device_token"`);
        await queryRunner.query(`DROP TABLE "temporary_device_token"`);
        await queryRunner.query(`DROP INDEX "IDX_b50fc7fc51f6222996f863de90"`);
        await queryRunner.query(`DROP INDEX "IDX_6fbd0029e33c03a79e873c34b7"`);
        await queryRunner.query(`DROP INDEX "IDX_60b09733c048fa94afb3581c62"`);
        await queryRunner.query(`DROP INDEX "IDX_60254057740731d5a0b07548f8"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"))`);
        await queryRunner.query(`INSERT INTO "users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
        await queryRunner.query(`DROP TABLE "event_beers"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar NOT NULL, "password" varchar, "name" varchar, "gender" varchar NOT NULL, "role" varchar NOT NULL DEFAULT ('PARTICIPANT'), "beerCount" integer NOT NULL DEFAULT (0), "lastBeerTime" datetime, "registrationToken" varchar, "isRegistrationComplete" boolean NOT NULL DEFAULT (0), "isTwoFactorEnabled" boolean NOT NULL DEFAULT (0), "twoFactorSecret" varchar, "isAdminLoginEnabled" boolean NOT NULL DEFAULT (0), "allowedIPs" text, "lastAdminLogin" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_436ea50c5ace989853a46210546" UNIQUE ("registrationToken"))`);
        await queryRunner.query(`INSERT INTO "users"("id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt") SELECT "id", "username", "password", "name", "gender", "role", "beerCount", "lastBeerTime", "registrationToken", "isRegistrationComplete", "isTwoFactorEnabled", "twoFactorSecret", "isAdminLoginEnabled", "allowedIPs", "lastAdminLogin", "createdAt", "updatedAt", "deletedAt" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
        await queryRunner.query(`CREATE INDEX "IDX_device_token_token" ON "device_token" ("token") `);
        await queryRunner.query(`ALTER TABLE "event_barrels" RENAME TO "temporary_event_barrels"`);
        await queryRunner.query(`CREATE TABLE "event_barrels" ("event_id" varchar NOT NULL, "barrel_id" varchar NOT NULL, CONSTRAINT "FK_event_barrels_barrel" FOREIGN KEY ("barrel_id") REFERENCES "barrels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_event_barrels_event" FOREIGN KEY ("event_id") REFERENCES "event" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("event_id", "barrel_id"))`);
        await queryRunner.query(`INSERT INTO "event_barrels"("event_id", "barrel_id") SELECT "event_id", "barrel_id" FROM "temporary_event_barrels"`);
        await queryRunner.query(`DROP TABLE "temporary_event_barrels"`);
        await queryRunner.query(`ALTER TABLE "event_users" RENAME TO "temporary_event_users"`);
        await queryRunner.query(`CREATE TABLE "event_users" ("event_id" varchar NOT NULL, "user_id" varchar NOT NULL, CONSTRAINT "FK_event_users_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_event_users_event" FOREIGN KEY ("event_id") REFERENCES "event" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, PRIMARY KEY ("event_id", "user_id"))`);
        await queryRunner.query(`INSERT INTO "event_users"("event_id", "user_id") SELECT "event_id", "user_id" FROM "temporary_event_users"`);
        await queryRunner.query(`DROP TABLE "temporary_event_users"`);
        await queryRunner.query(`ALTER TABLE "beers" RENAME TO "temporary_beers"`);
        await queryRunner.query(`CREATE TABLE "beers" ("id" varchar PRIMARY KEY NOT NULL, "userId" varchar NOT NULL, "barrelId" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "deletedAt" datetime, CONSTRAINT "FK_beers_barrel" FOREIGN KEY ("barrelId") REFERENCES "barrels" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_beers_user" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "beers"("id", "userId", "barrelId", "createdAt", "deletedAt") SELECT "id", "userId", "barrelId", "createdAt", "deletedAt" FROM "temporary_beers"`);
        await queryRunner.query(`DROP TABLE "temporary_beers"`);
        await queryRunner.query(`DROP INDEX "IDX_device_token_token"`);
        await queryRunner.query(`ALTER TABLE "device_token" RENAME TO "temporary_device_token"`);
        await queryRunner.query(`CREATE TABLE "device_token" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar NOT NULL, "deviceType" varchar NOT NULL DEFAULT ('web'), "deviceName" varchar, "deviceModel" varchar, "osVersion" varchar, "isActive" boolean NOT NULL DEFAULT (1), "lastUsed" datetime, "userId" varchar NOT NULL, "isAdminDevice" boolean NOT NULL DEFAULT (0), "biometricEnabled" boolean, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_device_token_user" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "device_token"("id", "token", "deviceType", "deviceName", "deviceModel", "osVersion", "isActive", "lastUsed", "userId", "isAdminDevice", "biometricEnabled", "createdAt", "updatedAt") SELECT "id", "token", "deviceType", "deviceName", "deviceModel", "osVersion", "isActive", "lastUsed", "userId", "isAdminDevice", "biometricEnabled", "createdAt", "updatedAt" FROM "temporary_device_token"`);
        await queryRunner.query(`DROP TABLE "temporary_device_token"`);
        await queryRunner.query(`CREATE INDEX "IDX_device_token_token" ON "device_token" ("token") `);
    }

}
